# roles/dnsmasq/tasks/main.yml
---
- name: Install Dnsmasq
  yum:
    pkg: dnsmasq
    state: present
  tags: dnsmasq

- name: Set configuration file
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    validate: 'dnsmasq --test --conf-file=%s'
  notify: restart dnsmasq
  tags: dnsmasq

- name: Make sure Dnsmasq is running
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags: dnsmasq

- name: Determine if firewalld installed
  command: "rpm -q firewalld"
  register: s
  changed_when: false
  failed_when: false
  always_run: yes

- name: Set the has_firewalld fact
  set_fact:
    has_firewalld: true
  when: s.rc == 0

- name: Determine if iptables-services installed
  command: "rpm -q iptables-services"
  register: s
  changed_when: false
  failed_when: false
  always_run: yes

- name: Set the has_iptables fact
  set_fact:
    has_iptables: true
  when: s.rc == 0

- include: firewalld.yml
  when: has_firewalld

- include: iptables.yml
  when: not has_firewalld and has_iptables
